export const initialKecerdasanQuestion = () => ({
  secureId: null,
  title: null,
  duration: 0,
  timer: 0,
  minutes: 0,
  seconds: 0,
  nowDate: null,
  nowHour: null,
  totalAnswer: null,
  questionIndex: 0,
  questions: [
    {
      secureId: null,
      sessionTime: null,
      question: {
        secureId: null,
        question: null,
        type: null,
      },
      answer: {
        secureId: null,
        answer: null,
        symbol: null,
        value: null,
        type: null,
      },
      answerList: [
        {
          secureId: null,
          symbol: null,
          answer: null,
          value: 0,
          type: null,
        },
        {
          secureId: null,
          symbol: null,
          answer: null,
          value: 0,
          type: null,
        },
        {
          secureId: null,
          symbol: null,
          answer: null,
          value: 0,
          type: null,
        },
        {
          secureId: null,
          symbol: null,
          answer: null,
          value: 0,
          type: null,
        },
        {
          secureId: null,
          symbol: null,
          answer: null,
          value: 0,
          type: null,
        },
      ],
    },
  ],
});
